apiVersion: v1
kind: Service
metadata:
  name: movie-api-service
spec:
  selector:
    app: movie-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30001
  type: NodePort
  