apiVersion: v1
kind: Pod
metadata:
  name: movie-api-pod
  labels:
    app: movie-api-pod
spec:
  containers:
    - name: movie-api-pod
      image: registry.hub.docker.com/kaanaydemir0/movie-api:0.0.3
      imagePullPolicy: IfNotPresent
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/movie
        - name: SPRING_DATASOURCE_USERNAME
          value: movie
        - name: SPRING_DATASOURCE_PASSWORD
          value: movie
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
          value: "true"
        - name: DIRECTOR-API_SERVICE_HOST
          value: http://director-api-clusterip-service
      ports:
        - containerPort: 8083
  restartPolicy: Always
##TEST
  